name = "SymmetricProducts"
uuid = "075c16e0-7ab9-11e8-024b-f7dece19ca2d"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "0.7"
